### ISSUE TITLE
Refactor code - tracker

### ISSUE THREAD

**Issue by Rot127** [rizinorg/rz-hexagon#52]
This issue tracks code to refactor.

- [ ] Documentation of structs should be Doxygen compliant (`//<` instead of `//`) 
- [ ] Unify "instruction" abbreviation`instr` -> `insn`.
- [ ] Run `clang-format` also over hand-written files. In case they were edited with indent style ignoring editors (e.g. vim)
- [ ] Enum names are sometimes all uppercase sometimes camel case. Should be all camel case.
- [ ] Add `const`, `RZ_BORROW` etc. qualifiers to all functions.
- [ ] Set internal functions to `RZ_IPI` instead of `RZ_API`
- [x] Fix grammar/spelling issues (`handwritten` -> `hand-written`)
- [x] Move the foloowing pattern in its own function
  ```python
  with open("handwritten/hexagon_il_h/include.h") as include:
    set_pos_after_license(include)
    code += "".join(include.readlines())
  ```
- [x] Move the following pattern in its own function:
  ```python
  if compare_src_to_old_src(code, path):
     self.unchanged_files.append(path)
     return
  with open(path, "w+") as dest:
     dest.writelines(code)
     log("analysis_hexagon.c written to {}".format(path), LogLevel.INFO)
   ```
- [x] Replaced `"..".format()` patterns with `f"..."` formatting in https://github.com/rizinorg/rz-hexagon/pull/60 
- [x]  Add functions which wrap code into a c-block/function/switch-case. (No longer needed since #60?)
- [x] Refactor `parse_instruction()`
  The method for parsing a Duplex or normal instruction are almost the same.
  The method should be in `InstructionTemplate` from which `DuplexInstruction` and `Instruction` inherit.
  
  Methods in question:
  https://github.com/rizinorg/rz-hexagon/blob/7df09f53826546b8e0a328021813882e13e21de1/DuplexInstruction.py#L99
  https://github.com/rizinorg/rz-hexagon/blob/7df09f53826546b8e0a328021813882e13e21de1/Instruction.py#L106

- [x] Update license date
- [x] Remove or include out-commented code (mostly logs)
